"""Bounded, evidence-grounded investigation for candidate merchant rings."""

from .contracts import (
    GroundingReport,
    GroundingStatus,
    Hypothesis,
    HypothesisKind,
    InformationRequestItem,
    InvestigationBudget,
    InvestigationResult,
    InvestigationStatus,
    InvestigatorOutput,
    Recommendation,
    ToolCallStatus,
    ToolObservation,
)
from .grounding import CitationValidator, summarize_grounding_failure
from .investigator import (
    AnthropicInvestigator,
    BoundedInvestigator,
    DeterministicInvestigator,
    DisabledProvider,
    InvestigatorProvider,
    ProviderDisabled,
    ProviderError,
    ScriptedProvider,
    build_investigator_provider,
)
from .memory import CaseMemory, PriorCaseRecord, PriorOutcome
from .tools import (
    TOOL_DESCRIPTIONS,
    TOOL_NAMES,
    EvidenceCatalogue,
    InvestigationToolbox,
    ToolError,
    build_evidence_catalogue,
    disclosed_evidence_ids,
)

__all__ = [
    "AnthropicInvestigator",
    "BoundedInvestigator",
    "CaseMemory",
    "CitationValidator",
    "DeterministicInvestigator",
    "DisabledProvider",
    "EvidenceCatalogue",
    "GroundingReport",
    "GroundingStatus",
    "Hypothesis",
    "HypothesisKind",
    "InformationRequestItem",
    "InvestigationBudget",
    "InvestigationResult",
    "InvestigationStatus",
    "InvestigationToolbox",
    "InvestigatorOutput",
    "InvestigatorProvider",
    "PriorCaseRecord",
    "PriorOutcome",
    "ProviderDisabled",
    "ProviderError",
    "Recommendation",
    "ScriptedProvider",
    "TOOL_DESCRIPTIONS",
    "TOOL_NAMES",
    "ToolCallStatus",
    "ToolError",
    "ToolObservation",
    "build_evidence_catalogue",
    "build_investigator_provider",
    "disclosed_evidence_ids",
    "summarize_grounding_failure",
]
